[package]
name = "scte35-editor-web"
version = "0.1.0"
edition = "2024"

[dependencies]
yew = { version = "0.21", features = ["csr"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hex = "0.4"
scte35 = { version = "0.2", features = ["base64"] }
web-sys = { version = "0.3", features = ["HtmlTextAreaElement", "HtmlSelectElement", "HtmlInputElement"] }
wasm-bindgen = "0.2"

[dependencies.scte35-editor]
path = ".."
default-features = false
